# Generated by Django 3.1.1 on 2020-09-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='iduid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ytvideo',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ytvideo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
